### ISSUE TITLE
来，7月份-今天的安排一下

### ISSUE THREAD

**Issue by Tacther** [iceBear67/Tacthers#1]
可以把事情本末发一下么，不要说~~你们~~我口吐芬芳的事情？大家都了解了解，不要学的和czm一样~~死皮不要脸~~容不得侵犯个人利益。

**Comment by Tacther** [comment]
![Uploading (5QRH@%M$5_Z[74)QPX{(_R.png…]()

**Comment by NaturalSelect** [comment]
Done

**Comment by Tacther** [comment]
包管理那是还不全吧
（顺带把前天我那个py协程发下
&nbsp;


3053434956
3053434956@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "自然选择"<notifications@github.com&gt;; 
发送时间: 2020年10月25日(星期天) 晚上11:38
收件人: "iceBear67/Tacthers"<Tacthers@noreply.github.com&gt;; 
抄送: "3053434956"<3053434956@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [iceBear67/Tacthers] 来，7月份-今天的安排一下 (#1)





 
Done
 
&mdash;

**Comment by Tacther** [comment]
Waiting for your DONE。
&nbsp;


3053434956
3053434956@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "自然选择"<notifications@github.com&gt;; 
发送时间: 2020年10月25日(星期天) 晚上11:38
收件人: "iceBear67/Tacthers"<Tacthers@noreply.github.com&gt;; 
抄送: "3053434956"<3053434956@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [iceBear67/Tacthers] 来，7月份-今天的安排一下 (#1)





 
Done
 
&mdash;

**Comment by Tacther** [comment]
爷想重开

**Comment by NaturalSelect** [comment]
您脑子没有问题？

**Comment by Tacther** [comment]
哦，那可以照顾一下残疾人吗？
&nbsp;


3053434956
3053434956@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "自然选择"<notifications@github.com&gt;; 
发送时间: 2020年10月27日(星期二) 晚上10:55
收件人: "iceBear67/Tacthers"<Tacthers@noreply.github.com&gt;; 
抄送: "3053434956"<3053434956@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [iceBear67/Tacthers] 来，7月份-今天的安排一下 (#1)





 
您脑子没有问题？
 
&mdash;

**Comment by Tacther** [comment]
你脑子没问题，有义务的呢。&nbsp;


3053434956
3053434956@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "自然选择"<notifications@github.com&gt;; 
发送时间: 2020年10月27日(星期二) 晚上10:55
收件人: "iceBear67/Tacthers"<Tacthers@noreply.github.com&gt;; 
抄送: "3053434956"<3053434956@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [iceBear67/Tacthers] 来，7月份-今天的安排一下 (#1)





 
您脑子没有问题？
 
&mdash;
